name: All subprojects

on:
  schedule:
    - cron: '22 1 5 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
            ~/go/
          key: golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-all-subprojects
          restore-keys: |
            golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-secrets
            golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
            golang-${{ runner.os }}
      - run: make ci
