name: All subprojects

on:
  schedule:
    - cron: '22 1 5 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
            ~/go/
          key: golang-${{ runner.os }}-all-subprojects-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            golang-${{ runner.os }}-secrets-${{ hashFiles('**/go.sum') }}
            golang-${{ runner.os }}-all-subprojects
            golang-${{ runner.os }}
      - run: make ci
      - uses: actions/upload-artifact@v3
        with:
          name: executables
          retention-days: 1
          path: |
            ./**/bin/*
