name: metal-id

on:
  push:
    paths:
      - 'metal-id/**'
      - '.github/workflows/metal-id*'
  pull_request:
    paths:
      - 'metal-id/**'
      - '.github/workflows/metal-id*'
  schedule:
    - cron: '15 14 1 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: metal-id
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
            ~/go/
          key: golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-metal-id
          restore-keys: |
            golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
            golang-${{ runner.os }}
      - run: make ci
