name: metal-id

on:
  push:
    paths:
      - 'metal-id/**'
      - '.github/workflows/metal-id*'
  pull_request:
    paths:
      - 'metal-id/**'
      - '.github/workflows/metal-id*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: metal-id
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
            ~/go/
          key: golang-${{ runner.os }}-metal-id-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            golang-${{ runner.os }}-all-subprojects-${{ hashFiles('**/go.sum') }}
            golang-${{ runner.os }}-metal-id
            golang-${{ runner.os }}-all-subprojects
            golang-${{ runner.os }}
      - run: make ci
