name: nbd

on:
  push:
    paths:
      - 'nbd/**'
      - '.github/workflows/nbd*'
  pull_request:
    paths:
      - 'nbd/**'
      - '.github/workflows/nbd*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nbd
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
            ~/go/
          key: golang-${{ runner.os }}-nbd-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            golang-${{ runner.os }}-all-subprojects-${{ hashFiles('**/go.sum') }}
            golang-${{ runner.os }}-nbd
            golang-${{ runner.os }}-all-subprojects
            golang-${{ runner.os }}
      - run: make ci
