name: secrets

on:
  push:
    paths:
      - 'secrets/**'
      - '.github/workflows/secrets*'
  pull_request:
    paths:
      - 'secrets/**'
      - '.github/workflows/secrets*'
  schedule:
    - cron: '22 1 5 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: secrets
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/
            ~/go/
          key: golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-secrets
          restore-keys: |
            golang-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
            golang-${{ runner.os }}
      - run: make ci
